{{- if .Values.service.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nfs-stale-exporter.fullname" . }}
  labels:
    {{- include "nfs-stale-exporter.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "nfs-stale-exporter.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.service.port }}
      targetPort: metrics
{{- end }}
