---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: nfs-stale-exporter
spec:
  selector:
    matchLabels: {app.kubernetes.io/name: nfs-stale-exporter}
  podMetricsEndpoints:
    - port: metrics
      interval: 30s
